# Generated by Django 5.0 on 2023-12-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsAccordion',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=50)),
                ('tittle', models.CharField(max_length=20)),
                ('toggle', models.CharField(blank=True, max_length=20)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsCard',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('icon', models.TextField(max_length=70)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('icon', models.TextField(max_length=70)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceBanner',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProduct',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('discount', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FaqQuestions',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('toggle', models.CharField(blank=True, max_length=20)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ForBlog',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=20)),
                ('dateAttr', models.CharField(max_length=30)),
                ('day', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('commCount', models.IntegerField()),
                ('publisher', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=10)),
                ('subtitle', models.TextField()),
                ('single', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalClients',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=50)),
                ('hover', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalHeader',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalTeam',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.TextField(max_length=100)),
                ('content', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalTestimonial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=30)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IconBox',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=70, unique=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('subtitle', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBox',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('subtitle', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceNavbar',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SideBarCategories',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
