# Generated by Django 5.0 on 2023-12-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalheader',
            name='link',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iconbox',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='servicebox',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
