# Generated by Django 5.0 on 2023-12-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_globalheader_link_alter_iconbox_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalheader',
            old_name='tittle',
            new_name='title',
        ),
    ]
