# Generated by Django 5.0 on 2023-12-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_rename_tittle_globalheader_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('phoneNumber', models.PositiveIntegerField()),
                ('eMail', models.EmailField(max_length=50)),
                ('healthComplaints', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='aboutusaccordion',
            old_name='tittle',
            new_name='title',
        ),
    ]
