# Generated by Django 5.0 on 2023-12-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_appointments_rename_tittle_aboutusaccordion_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('phoneNumber', models.PositiveIntegerField()),
                ('eMail', models.EmailField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('message', models.PositiveIntegerField()),
            ],
        ),
    ]
