# Generated by Django 5.0 on 2023-12-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_alter_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='eMail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='fullName',
            new_name='your_name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='phoneNumber',
            new_name='your_phone',
        ),
    ]
