# Generated by Django 5.0 on 2023-12-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_rename_email_message_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='your_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='your_phone',
            new_name='phone',
        ),
    ]
