# Generated by Django 5.0 on 2023-12-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_rename_your_name_message_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='title',
        ),
    ]
