# Generated by Django 5.0 on 2023-12-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0009_rename_name_message_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='name',
        ),
    ]
