# Generated by Django 5.0 on 2023-12-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0012_message_name_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='venue',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
