# Generated by Django 5.0 on 2023-12-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0013_message_phone_message_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
